### ISSUE TITLE
How to use it in AWS Lambda?

### ISSUE THREAD

**Issue by asaarashi** [branchenergy/lambda-handler#8]
I am a newbie to Lambda. I copied the below codes to my `lambda_function.py` and created a layer for all the libs, when I run the Lambda, it throws an error stating that lambda_handler isn't in the lambda function.
```
from fastapi import FastAPI
from lambda_handler import LambdaHandler, SnsEvent, LambdaResponse

handler = LambdaHandler()
...........
handler.fastapi_app = app
```

**Comment by badge** [comment]
@asaarashi hey, in this case the handler is `handler`, so you need to reference `lambda_function.handler` in the Lambda function defintion in the AWS UI.
